development:
  clients:
    default:
      database: hanks_hou_development
      hosts:
        - localhost:27017

  options:

production:
  sessions:
    default:
      database: hanks_hou_production
      hosts:
        - localhost:27017
  options:

test:
  clients:
    default:
      database: hanks_hou_test
      hosts:
        - localhost:27017
