development:
  clients:
    default:
      database: hanks_hou_development
      hosts:
        - localhost:27017
      username: hanks
      password: hanks1234

  options:

production:
  sessions:
    default:
      database: hanks_hou_production
      hosts:
        - localhost:27017
      username: hanks
      password: hanks1234
  options:

test:
  clients:
    default:
      database: hanks_hou_test
      hosts:
        - 127.0.0.1:27017
